name: .NET Format Check

on:
  push:
    branches: [ \
**\ ]
  pull_request:
    branches: [ \**\ ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dotnet-format
      run: dotnet tool install -g dotnet-format

    - name: Check formatting
      run: dotnet-format --folder --check --verbosity diagnostic
